### ISSUE TITLE
Who are the readers of the docs?

### ISSUE THREAD

**Issue by abitmore** [cedar-book/BTS-Core-work#3]
It's not clear to me who will be reading the docs. AKA we need a good UX-design, so people can get started quickly, and get needed info easily.

Here are some wild thoughts.

Is this an overall doc site, or only for developers?

It's best to have a system overview, like those in https://www.google.com/search?q=system+overview&tbm=isch.

* system components (the outside, network architecture)
  * short description of each
  * how they're connected (protocol)

* inside system: data structure, consensus
  * accounts
  * assets
  * voting
  * ...

* people (roles) involved / services around
  * what do they do

* How to get started (for businesses, integration guide)
  * if you're an external exchange
  * if you want to run an exchange on top of BitShares
  * if you're a merchant, or want to build tools for merchants, to accept bitUSD or etc
  * if want to build data query or analysis service
  * want to build tools for trading
  * ...

* How to get started (steps for developers)
  * if you're a backend developer
  * if you're a web developer
  * if you're a mobile app developer
  * script developer
  * ...

* How to get started (for users)
  * download light wallet or use web wallet
  * create an account
  * transfer
  * trade
  * ...

* for advanced users
  * issue an asset
  * botting
  * ...

**Comment by cedar-book** [comment]
About System overview. It might be needed to update but I like that the System overview BTSwolf created.   I added a link on [References](https://github.com/bitshares/how.bitshares.works/blob/master/developers/2_references_tools/references.md#references) page right now.  How do you like them? 
[BitShares - Basic Connections Layer](https://steemit.com/bitshares/@btswolf/bitshares-basic-connections-layer) : infographic - basic overview - BTSwolf

**Comment by abitmore** [comment]
The linked infographic is a good one. It shows some "people (roles) involved / services around" listed in OP. We also need other graphics.

BTW references page has changed to [this](https://github.com/bitshares/how.bitshares.works/blob/master/developers/references_tools/references.md).

**Comment by cedar-book** [comment]
Hi @abitmore, I have been keeping your above message on my note. But it seems I had been going somewhere. I had thought the list would be in my mind to work on but seems not.  I appreciate your patients to giving me comments. But I am not doing good job to make the list.

**Comment by cedar-book** [comment]
This category: How to get started (for businesses, integration guide).  I am trying to think but I do not know well about those actual Businesses. So, I cannot see or tell how they do their businesses and what they might need .  So, I would like to look into the "system comportment and structures" sections.

**Comment by abitmore** [comment]
Re-posted to https://github.com/bitshares/how.bitshares.works/issues/35, hope that we can get more people involved. Thanks for your efforts anyway. I haven't been paying attention to this issue either, sorry for that.
